### ISSUE TITLE
Process should exit with failure code if there are errors

### ISSUE THREAD

**Issue by igorpupkinable** [vytenisu/npm-dts#13]
I am testing this tool to generate declarations. I would like to add it to our CI pipeline.
Unfortunately, this tool still exits successfully even if declarations fail to generate.
I only see `[npm-dts] [error] : Generation failed!` error message, but process does not terminate with failure.

Where is the right place to add `process.exit(1)` in the code if error occurs?

Thanks.

**Comment by vytenisu** [comment]
Hi @igorpupkinable. Very good point! Tbh I am slightly surprized I did not do it already an no-one complained :D

Fix would be making sure that "generate" method rejects promise in case of error and then in cli.js need to make sure that process returns error code.

Should not be a big deal to fix. I will have a look in a few days.

**Comment by vytenisu** [comment]
Please try version 1.3.8. It should now exit CLI with code 1 in case of exception.

Out of curiosity it would be interesting to learn how you use the tool and how you integrate it into your CI.

Also, since I am not fully sure how you integrate tool into CI, please note that in case you integrate not directly via CLI but instead use some JS script which then launches Generator from npm-dts - you need to initialize Generator by passing third argument as true to the constructor.

Also, if you perform a build step for your code in CI, note that there is npm-dts-webpack-plugin (if you use Webpack) - it might be more convenient to integrate.

I will be closing this task for now. Please let me know if fix works. Otherwise - feel free to re-open.
