### ISSUE TITLE
Error: Declaration emit for this file requires using private name

### ISSUE THREAD

**Issue by aboveyunhai** [vytenisu/npm-dts#26]
Hi, I'm not sure I used this packages correctly.
I create a subfolders from the project and then `npm install package` inside that folder with only packages I want. 
Lastly, run `npm-dts`, but got a bunch of errors like `error TS9005: Declaration emit for this file requires using private name 'LiveRegion'. 
An explicit type annotation may unblock declaration emit.`

the directory structure: 

subfolder
- package.json
- package-lock.json
- tsconfig.json
- node_modules

tsconfig.json: 
```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "ES6"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": [
    "node_modules/@chakra-ui/**/*"
  ],
  "exclude": []
}
```

package.json
```json
{
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "type-gen-wins": "%INIT_CWD%/node_modules/.bin/npm-dts -L debug --output index.d.ts generate",
    "type-check": "tsc"
  },
  "dependencies": {
    "@chakra-ui/react": "^1.7.1",
    "@emotion/react": "^11.6.0",
    "@emotion/styled": "^11.6.0",
    "framer-motion": "^4.1.17"
  },
  "devDependencies": {
    "npm-dts": "^1.3.10"
  }
}
```

Sorry for dumping a lot of things, I know it's not supported to be Stackoverflow.

**Comment by vytenisu** [comment]
I am not entirely sure but it seems as if you are attempting to generate typings for another module inside _node_modules_. Normally that module should bring its own typings together with compiled _JavaScript_ files OR it should provide plain _TypeScript_ sources. In this case it seems that _@chakra-ui_ provides _TypeScript_ files so you should be able to import them directly in some _TypeScript_ project and build them together with your project's source.

If your project is _JavaScript-based_ you might in fact need to compile that library first. If you just build it using TSC it should generate a _JavaScript_ file next to each _TypeScript_ file and that should allow you to consume it.

_npm-dts_ would be used if you were a developer of _@chakra-ui_ and you would want to publish a pre-built minimized version of the library without original source code. In such case ideally _@chakra-ui_ project would import _npm-dts_ or _npm-dts-webpack-plugin_ and use it to produce _index.d.ts_ which could then be used for type suggestions.

Now, even though I do not think you needed _npm-dts_ for your use case, let's see what is happening. If your sub-folder only contains those 4 files - I don't think that _npm-dts_ would work at all. By default it is looking for _index.ts_ entry file in the root folder which is by default current working directory (same as package.json path). Hence I would expect _npm-dts_ to not be able to find it at all and fail (though error message seems a bit weird). Entry file name and root folder name can be changed manually using _--entry_ and _--root_. You do not need to specify output in your case because it is "index.d.ts" by default. But having said that - I am not sure what purpose it would serve and what problem you are trying to solve.

Hope it gives some thoughts.

**Comment by aboveyunhai** [comment]
Wow, I don't expect you can give me such amount of quality info. And indeed I misuse your package based on your explanation.

My original intend of using this package is to "summarize" all the typescript definitions from chakra into one.

**Comment by vytenisu** [comment]
For the sake of experiment, you could clone **@chakra-ui**, install _npm-dts_ and run it for every component (because every component is a separate package). Just make sure you either run _npm-dts_ from folders of those components or manually set root to them. This should create "index.d.ts" in each package. If you would then want to have one huge index.d.ts with all components in it, you might just need to simply concatenate all of individual index.d.ts files into one without changing anything in them.

In theory it should be doable inside node_modules as well without cloning git.

Not sure if it is worth doing that but you can try this approach - it should work I think.

**Comment by aboveyunhai** [comment]
> For the sake of experiment, you could clone **@chakra-ui**, install _npm-dts_ and run it for every component (because every component is a separate package). Just make sure you either run _npm-dts_ from folders of those components or manually set root to them. This should create "index.d.ts" in each package. If you would then want to have one huge index.d.ts with all components in it, you might just need to simply concatenate all of individual index.d.ts files into one without changing anything in them (npm-dts namespaces everything with package name so I would expect no type clashes).
> 
> In theory it should be doable inside node_modules as well without cloning git.
> 
> Not sure if it is worth doing that but you can try this approach - it should work I think.

Thx for your suggestion. I will try it out tomorrow and see how it was handled via your package. Do you mind just keep the issue open right now, so I can leave some feedbacks before I closed it

**Comment by vytenisu** [comment]
Sure, no probs.

**Comment by WhiteTurbine** [comment]
@aboveyunhai, I can see you have closed the issue. Just curious - did you find some other solution to your problem, decided to leave it as is or did last suggestion help?

**Comment by aboveyunhai** [comment]
> @aboveyunhai, I can see you have closed the issue. Just curious - did you find some other solution to your problem, decided to leave it as is or did last suggestion help?

In fact, I was examining multiple similar tools as well as how Ts parsing works. I'm too naive to make further conclusion. It seems like each tool has its own limitations, target senario, and something that I'm not aware of. 
I'm still in the newbie stage to understand them.

**Comment by WhiteTurbine** [comment]
@aboveyunhai, to setup build with TS parsing for your project I would recommend using WebPack with typescript and ts-loader. See here: https://webpack.js.org/guides/typescript/. Simplest way to compile TS into JS is to run TSC command line utility which is part of typescript npm package but under normal conditions you want to add additional configuration, minimize your code, etc. This is why I would suggest using WebPack. If you are experimenting with React, try using "create-react-app" npm package and setup your initial project automatically using command:

`npx create-react-app my-app --template typescript`

Tools like npm-dts and similar are more for various corner cases. I don't think you should start learning by exploring these. Under most circumstances you will not need them.

**Comment by aboveyunhai** [comment]
> @aboveyunhai, to setup build with TS parsing for your project I would recommend using WebPack with typescript and ts-loader. See here: https://webpack.js.org/guides/typescript/. Simplest way to compile TS into JS is to run TSC command line utility which is part of typescript npm package. It would generate JS for every TS file you have. However, under normal conditions you want to add additional configuration, minimize your code, etc. This is why I would suggest using WebPack. If you are experimenting with React, try using "create-react-app" npm package and setup your initial project automatically using command:
> 
> `npx create-react-app my-app --template typescript`
> 
> If you use eject command from create-react-app, you would see how project can be setup.
> 
> Tools like npm-dts and similar are more for various corner cases. I don't think you should start learning by exploring these. Under most circumstances you will not need them.

Thx for your suggestion, I'm actually solving some cases with these tools, not general `tsc`. What I mean learning is how these tools work internally.

**Comment by arei** [comment]
Late to the party here, but I solved this for a similar by adding a JSDoc `@type` comment above the offending thing. In my case I had a class that had a getter which returned a different class and any usage of the getter would give this error.

So this...
```
// File Foo.js
class Foo {
  get Bar() {
    return Bar;
  }
}
class Bar {};

// File Blah.js
const Foo = require('./Foo.js');
class Blah extends Foo.Bar {}      <--- Error would be here
```

Is fixed by this...
```
  /**
   * @type Class
   */
  get Bar() {
    return Bar;
  }
```
