### ISSUE TITLE
Only initially use one file (--entry)

### ISSUE THREAD

**Issue by Lawlzer** [vytenisu/npm-dts#35]
Hello! I am trying to get all of the types used in one file, and any types referenced from that file, into one file. 

I made an example repo to easily showcase this:
https://github.com/Lawlzer/TEMPORARY-npm-dts-thing-DO-NOT-USE

As an example, with a command like this:
`npm-dts generate -e .\src\bar\index.ts`
I would expect to only see `src/bar/index.ts`, and `src/bar/util.ts` referenced -- but this isn't how it works. Instead, it *also* mentions `src/foo` -- but these are entirely unrelated to `bar/index.ts`!

Am I misunderstanding how Entry works / doing it wrong? Or is this something this package isn't meant to do? (Purely for all-file-transpilation?)
Thanks in advance! This package is nicely done, and I greatly appreciate any help :)

**Comment by vytenisu** [comment]
**npm-dts** is a rather simple package. It mainly concatenates d.ts files which are generated by tsc, performs some minor modifications and adds additional code to output d.ts which allows referencing entry file by package name directly (like `import smth from 'your-package';` instead of `import smth from "your-package/some-module`). This can be used for various use cases such as publishing a pre-bundled package with type support.

I guess you need something similar to what @htho tried to achieve with proposed `--shake` property. You can find our communication here: https://github.com/vytenisu/npm-dts/pull/33. Perhaps he could share his fork with you. I feel guilty right now that I have not finalized review of that PR yet...

In theory you could manually configure how you want to compile passing options to TSC via "--tsc" but I understand that this is probably not what you want to achieve.

**Comment by htho** [comment]
Hi,

You can find my fork here: https://github.com/htho/npm-dts
I also published an npm package @htho/npm-dts it also takes d.ts files in the source tree.

Feel free to use it, but I don't have much time to maintain it.
