### ISSUE TITLE
Is there a way to specify the output directory?

### ISSUE THREAD

**Issue by promethyttrium** [vytenisu/npm-dts#4]
First off, I think this is the ONLY solution that I've found that's easy to use and actually works. Thanks for doing this!!

Can you please tell me if there's an option to specify the output directory? My built files are in the `dist` folder so I would like the `.d.ts` file to be in that folder before I publish. Right now, I have to "manual" `mv` it into the dist folder. Would be nice if there's a way for it to be automatic.

Thanks!!

**Comment by vytenisu** [comment]
Hey @promethyttrium . I am happy you find the solution useful!

At the moment there is no option allowing to change output location / name. The reason is - if you add index.d.ts directly into root - it gets automatically detected by TS when your library is consumed without any additional configuration in package.json.

When I build my own libraries, I do same as you - I output my build artifacts to "dist". However, I leave "index.d.ts" in root and ignore it in my .gitignore

Having said above, what do you think - do you still need an option to change output directory or perhaps saving into root is better?

**Comment by robert-cronin** [comment]
I would love a way to specify the output directory :+1:

**Comment by vytenisu** [comment]
Alright then. Will add new option sometime in the coming days. Will update here.

**Comment by vytenisu** [comment]
Can you please try v1.3.0 and see if it works? There is "-o" option which allows to change name or location of index.d.ts. Basically it is a path to output file relative to root of target project.
