### ISSUE TITLE
support path mapping

### ISSUE THREAD

**Issue by RichardLuo0** [vytenisu/npm-dts#6]
For module using path mapping, I hope it can replace path alias automatically. 
For example, I have the following in my tsconfig.json:
```
"compilerOptions": {
        "paths": {
            "@/*": [
                "src/main/*"
            ]
        },
}
```
npm-dts will replace "@/" with the corresponding path so that I don't have to replace them manually

**Comment by vytenisu** [comment]
Hi Richard, will have a look at path mapping at some point soon. Tbh I normally do not use mapping like that in my projects so I did not test this use case yet.

**Comment by vytenisu** [comment]
Took me some time till I was able to spend time and investigate. It looks like "paths" are not mapped when compiling and/or generating d.ts files on purpose by TSC itself. If I understand correctly, "paths" is basically a hint for compiler needed to perform static code analysis. Non-mapped module name can be perfectly valid at runtime and therefor it is not substituted.

There is a good answer here about "paths":
https://github.com/microsoft/TypeScript/issues/9910#issuecomment-234729007

Worth mentioning there are modules which do perform path mapping during build but due to reasons provided I do not believe this is in scope of npm-dts. npm-dts uses TSC "as is" to avoid complexity, make sure tool is stable and easy to maintain.

Please let me know if you have any further concerns.
